/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    PlayerBar: typeof import('./src/components/PlayerBar.vue')['default']
    QueuePanel: typeof import('./src/components/QueuePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarPlaylists: typeof import('./src/components/SidebarPlaylists.vue')['default']
    SonosPanel: typeof import('./src/components/SonosPanel.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
